### ISSUE TITLE
总有一群总自以为是的人，觉得自己很牛b的存在，实际只是个键盘侠，人云亦云，别说看得懂liteos了，估计c都没写过1000行。是不是面试被拒了怀恨在心呀。。。

### ISSUE THREAD

**Issue by nerososft** [monyhar/monyhar-lite#123]

**Comment by Jefferyu** [comment]
多少年了，终于迎来了我们第一个全自主研发的浏览器，一路走来太不容易了，外面制裁打压，内部质疑抹黑，这是一条前无古人的伟大道路，未来可期的伟大道路，即便再多的艰难险阻都无法阻挡梦弘不断突进，这条路将越走越宽，越走越光明，层出不穷的质疑抹黑的汉奸走狗终将被钉在耻辱柱上

**Comment by liyangSuperNb** [comment]
为什么不支持中国人自己的浏览器？你是不是中国人？

**Comment by tgxhx** [comment]
你发这些有什么目的？谁指使你的？你的动机是什么？你取得有关部门许可了吗？他们容许你发了吗？你背后是谁，发这些想做什么？你在讽刺谁？想颠覆什么？破坏什么？影射什么？回答不上来？那么跟我走一趟，顺便把你家户口本带上取证！别说我们瞎抓你，都是有理有据的！

**Comment by jingyuexing** [comment]
> 你发这些有什么目的？谁指使你的？你的动机是什么？你取得有关部门许可了吗？他们容许你发了吗？你背后是谁，发这些想做什么？你在讽刺谁？想颠覆什么？破坏什么？影射什么？回答不上来？那么跟我走一趟，顺便把你家户口本带上取证！别说我们瞎抓你，都是有理有据的！

蚌埠住了蚌埠住了

**Comment by ghost** [comment]
这个嘴巴不干净的人被论坛扒出来了，确定目前是华为的正式员工。

然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？

**Comment by ghost** [comment]
哈哈哈哈他怂了，他把自己的评论全删了，然而我备份了：

<https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225>

让大家看看，这就是刚刚在 GitHub 上嘲笑其他开发者，说别人是怂蛋的华为员工。如此气势汹汹，居然连自己说的话都不敢留。

**Comment by wsdjeg** [comment]
原来是 https://github.com/SynestiaOS/SynestiaOS 的 author

**Comment by nerososft** [comment]
> 原来是 https://github.com/SynestiaOS/SynestiaOS 的 author

我看了https://www.openharmony.cn/#/ebooka?url=%3A443%2Fhtml_from_md%2F1622598005475&name=%E4%BB%A3%E7%A0%81%E4%B8%8B%E8%BD%BD 这个东西，感觉还可以呀，不知道为啥要搞个阴阳怪气的项目在这儿。
