### ISSUE TITLE
不是蠢就是坏，要么就是面试被拒怀恨在心。。

### ISSUE THREAD

**Issue by nerososft** [monyhar/monyhar-lite#125]

**Comment by Jefferyu** [comment]
多少年了，终于迎来了我们第一个全自主研发的浏览器，一路走来太不容易了，外面制裁打压，内部质疑抹黑，这是一条前无古人的伟大道路，未来可期的伟大道路，即便再多的艰难险阻都无法阻挡梦弘不断突进，这条路将越走越宽，越走越光明，层出不穷的质疑抹黑的汉奸走狗终将被钉在耻辱柱上

**Comment by beimenzhao** [comment]
傻子都知道，monyhar做完全独立浏览器会死，就是现在基于chromium又能怎样，关键问题是老美要卡脖子的时候，monyhar能不能用，这才是关键

**Comment by tgxhx** [comment]
看这问题问的，你能真实的感受到某些人的不甘心。

Monyhar出来了，而且能用，怎么办，怎么办，怎么办？？

隔着屏幕都能感受到的焦虑。

很多人说，有什么了不起，不过是改了一个Chromium，我也能做到。

还有人说，华为的浏览器一点不比Monyhar差，积累的经验更丰富，同样有万物互联的追求。

还有人说，这群人就是会宣传，爱国绑架，无数人都被蒙骗了，于是Monyhar变成了，蒙了又哄。

焦虑，满屏的焦虑。无处释放的焦虑感。

这让他们除了攻击开发者，攻击Monyhar，没有任何方法可以排解。

唉........

**Comment by ghost** [comment]
这个人被论坛扒出来了，确定目前是华为的正式员工。

然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提两个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？如何看待某华为员工在 GitHub 上群嘲其他开发者？

详见：#123 [#225](https://github.com/monyhar/monyhar/issues/225)
