### ISSUE TITLE
丢人丢到国外了吗？这又不是微博

### ISSUE THREAD

**Issue by scwelcome** [monyhar/monyhar-lite#143]

**Comment by ultimateHandsomeBoy666** [comment]
难道不是鸿蒙丢人丢到国外去了？只敢在国内忽悠不懂得国人

**Comment by mem4tgo** [comment]
你个

> 难道不是鸿蒙丢人丢到国外去了？只敢在国内忽悠不懂得国人

汉奸！

**Comment by mem4tgo** [comment]
> _No description provided._

你居然说国产自主研发的浏览器丢人？是不是立场有问题？谁没有从0开始的一步？以后就是上亿步！

**Comment by NiceSprite34** [comment]
收拜登黑钱？不支持国产？你个狗汗奸

**Comment by koubun-ko-df** [comment]
外国人看不懂的啦

**Comment by luodi1990** [comment]
不能给国产软件一点时间？这么急着跳出来质疑国产软件，你是收了拜登的狗粮吧。

**Comment by 253681319** [comment]
丢人？什么叫丢人，自研丢人，用一点别人的代码丢人？
什么叫又不是微博？在微博上就可以不要脸了吗？
