### ISSUE TITLE
SB

### ISSUE THREAD

**Issue by lcztt** [monyhar/monyhar-lite#169]
DSB

**Comment by luych** [comment]
issue是让你提议题的 不是让你自我介绍的 :-1:

**Comment by lcztt** [comment]
有你这种DSB才是真丢人，丢人都丢到国外去

**Comment by lcztt** [comment]
我TM想不明白黑HW对你有啥好处，就跟那帮整天鼓吹外国武器比国内好的那帮人一样一样的，国内武器再差也是保护国人，外国武器再好也TM是杀你的

**Comment by mckuhei** [comment]
差不多得了😅😅😅
