### ISSUE TITLE
解锁新领域: 高级黑

### ISSUE THREAD

**Issue by UpKiry** [monyhar/monyhar-lite#177]
鸿蒙操作系统 自主研发版本 - 完全自主研发，打破国外垄断，比 Android 快 600%。缺少软件代码。

**Comment by UpKiry** [comment]
我真的搞不懂华为这几场的 “开发者大会” 开了些什么

发几张好看的 PPT 又不公布技术细节

现在公测之后又被程序员扒出抄袭 Android，算个*的国产自研，还是在 Google 的五指山之间跳来跳去

我是中国人，不是水军，不玩爱国主义的游戏

我支持鸿蒙，支持木兰，支持汉芯

但是我不支持抄袭，不管是国内的，国外的，中国的，还是世界的

更不支持华为这样的 500 强企业，老牌企业，中国的复兴之光，玩这种小伎俩

请对技术秉持最基本的尊重与敬畏

请不要把中国人的脸丢到国外

**Comment by freefishgo** [comment]
> 我真的搞不懂华为这几场的 “开发者大会” 开了些什么
> 
> 发几张好看的 PPT 又不公布技术细节
> 
> 现在公测之后又被程序员扒出抄袭 Android，算个*的国产自研，还是在 Google 的五指山之间跳来跳去
> 
> 我是中国人，不是水军，不玩爱国主义的游戏
> 
> 我支持鸿蒙，支持木兰，支持汉芯
> 
> 但是我不支持抄袭，不管是国内的，国外的，中国的，还是世界的
> 
> 更不支持华为这样的 500 强企业，老牌企业，中国的复兴之光，玩这种小伎俩
> 
> 请对技术秉持最基本的尊重与敬畏
> 
> 请不要把中国人的脸丢到国外

抄袭也没什么，主要是不要误导人
