### ISSUE TITLE
有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇

### ISSUE THREAD

**Issue by KeatsLi** [monyhar/monyhar-lite#259]
战士战死了的时候，苍蝇们所首先发见的是他的缺点和伤痕，嘬着，营营地叫着，以为得意，以为比死了的战士更英雄。但是战士已经战死了，不再来挥去他们。于是乎苍蝇们即更其营营地叫，自以为倒是不朽的声音，因为它们的完全，远在战士之上。
的确的，谁也没有发见过苍蝇们的缺点和创伤。
然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。
去罢，苍蝇们！虽然生着翅子，还能营营，总不会超过战士的。你们这些虫豸们！

鸿蒙的发展，或许三年不可，或许五年无成，但数十载过后，定会有所不同。

**Comment by DarinzyGH** [comment]
把一家弄虚作假的资本家企业吹成形象高大伟岸的英雄勇士，好像没了它国家会死一样，好像只有它在对抗敌人一样，宣传上混淆视听，一次次消耗人民的信任，高价割自己人的韭菜，怎么会有这么下贱的行为？地球没了你照样转，你的人可以被吸收，你的位置一样有人填补，不发展教徒，不搞饭圈kol那套，实事求是会死？搞得自己多无辜，你认为这是一种健康可持续的模式？不过因为要吃饭搞了下作的宣传而已，利用成熟的开源项目二次开发本是业内行规，无可厚非，你实事求是没人说你什么

**Comment by Iridescentangle** [comment]
鸿蒙的发展，或许三年不可，或许五年无成，但数十载过后，定会有所不同！！！

**Comment by KeatsLi** [comment]
> 把一家弄虚作假的资本家企业吹成形象高大伟岸的英雄勇士，好像没了它国家会死一样，好像只有它在对抗敌人一样，宣传上混淆视听，一次次消耗人民的信任，高价割自己人的韭菜，怎么会有这么下贱的行为？地球没了你照样转，你的人可以被吸收，你的位置一样有人填补，不发展教徒，不搞饭圈kol那套，实事求是会死？搞得自己多无辜，你认为这是一种健康可持续的模式？不过因为要吃饭搞了下作的宣传而已，利用成熟的开源项目二次开发本是业内行规，无可厚非，你实事求是没人说你什么

不管于国于民，华为的贡献远非你这样的宵小之辈可以企及，苍蝇永远是苍蝇，文明的进步，社会的发展，都不是你这种人可以推动的。苍蝇的就是自身毫无价值，依靠自以为是的聪明去诋毁，去嘲讽，来突显得自己的智慧，自己的声音。

**Comment by KeatsLi** [comment]
于国，华为每年为国家贡献了超千亿的税收
于民，华为为通讯事业贡献了不可或缺的力量，让中国在4g和5g的发展上领先诸国，让大众用上廉价的网络通讯，促进了互联网的发展，
于中国年轻人，华为提供了数以十万计的优质高薪岗位。

于国于民，于未来，大至人类文明，小至社会发展，需要的都是这样的组织，这样的个人，而不是一辈子只会嘲讽，阴阳怪气，嗡嗡乱叫，怯弱无为的苍蝇。

**Comment by DarinzyGH** [comment]
> > 把一家弄虚作假的资本家企业吹成形象高大伟岸的英雄勇士，好像没了它国家会死一样，好像只有它在对抗敌人一样，宣传上混淆视听，一次次消耗人民的信任，高价割自己人的韭菜，怎么会有这么下贱的行为？地球没了你照样转，你的人可以被吸收，你的位置一样有人填补，不发展教徒，不搞饭圈kol那套，实事求是会死？搞得自己多无辜，你认为这是一种健康可持续的模式？不过因为要吃饭搞了下作的宣传而已，利用成熟的开源项目二次开发本是业内行规，无可厚非，你实事求是没人说你什么
> 
> 不管于国于民，华为的贡献远非你这样的宵小之辈可以企及，苍蝇永远是苍蝇，文明的进步，社会的发展，都不是你这种人可以推动的。苍蝇的就是自身毫无价值，依靠自以为是的聪明去诋毁，去嘲讽，来突显得自己的智慧，自己的声音。

除了转移话题尬吹还会啥？烟草税收不完爆你？其他公司没提供就业岗位没纳税？自己他妈天天意淫自己站在很高的角度一样，俯瞰众生，好有优越感哦，你又天天推动了什么啊？没有基层的人民，一线人员，你也是一坨屎，你不是唯一，你也不是不可取代，归根到底就虚假宣传的问题还能扯这么多，扣这么多帽子，圣母玛利亚见了你们都想让位，少造神，多实事求是

**Comment by yorange1** [comment]
如果觉得有被嘲讽和诋毁到，正好说明了鸿蒙到底是不是高大伟岸，今天有梦弘，就是因为昨天有鸿蒙，长久以往，则国内处处是梦弘。

**Comment by KeatsLi** [comment]
多年以后，历史会证明一切，与苍蝇争论，毫无意义。烟草石油等行业贡献的高税收主要是因为国有垄断，而华为等民营企业的高税号，则是靠自己创建的社会价值。
任何一家贡献了高额税收，提供了优质就业岗位的企业或个人不比尔等苍蝇对社会价值高。
我从来没有说华为是完美的，事实上从古至今，也没有任何国家，任何企业，任何组织或个人没做做过恶，美国如此，中国如此，苹果谷歌微软如此，华为阿里腾讯如此，但是瑕不掩瑜，但凡一个脑子没问题的人，都能看到他们对社会发展的贡献和推进是远大于他们做的恶。只有苍蝇，盯着别人的伤口，叫个不听，仿佛看到了别人的伤口，就能凸现自己的伟大睿智，自己的清醒与独立，实则可悲可笑。

**Comment by yorange1** [comment]
> 多年以后，历史会证明一切，与苍蝇争论，毫无意义。烟草石油等行业贡献的高税收主要是因为国有垄断，而华为等民营企业的高税号，则是靠自己创建的社会价值。
> 任何一家贡献了高额税收，提供了优质就业岗位的企业或个人不比尔等苍蝇对社会价值高。
> 我从来没有说华为是完美的，事实上从古至今，也没有任何国家，任何企业，任何组织或个人没做做过恶，美国如此，中国如此，苹果谷歌微软如此，华为阿里腾讯如此，但是瑕不掩瑜，但凡一个脑子没问题的人，都能看到他们对社会发展的贡献和推进是远大于他们做的恶。只有苍蝇，盯着别人的伤口，叫个不听，仿佛看到了别人的伤口，就能凸现自己的伟大睿智，自己的清醒与独立，实则可悲可笑。

真正的战士为了实事求是努力奋斗，真正的苍蝇毫无头脑的站队沸腾，就算别人没有伤口，也要叫个不听，仿佛叫个不停就能凸现自己的伟大睿智，自己的清醒与独立，实则可悲可笑。华为挺多只是为了自己企业的利益虚假宣传，你们这群苍蝇天天沸腾才是真正的把华为架上油锅，阻碍国家基础软件行业的发展。不惜牺牲整个国家基础软件行业的发展，只为了彰显自己的与众不同，实乃真正的卖国投降行径。
