### ISSUE TITLE
你是不是以为自己很幽默？

### ISSUE THREAD

**Issue by leung13** [monyhar/monyhar-lite#81]
你是不是以为自己很幽默？可以不爱 没必要这样像个小丑那样 你要去马戏团当我没说

**Comment by isherryforever** [comment]
+1

**Comment by miyokor** [comment]
+1

**Comment by ZerOri** [comment]
拿GitHub当化粪池呢这，biss

**Comment by Zxilly** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7667
我寻思怎么会有人在英文项目发中文呢？原来是小丑啊

**Comment by ZerOri** [comment]
> [tachiyomiorg/tachiyomi-extensions#7667](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7667)
> 我寻思怎么会有人在英文项目发中文呢？原来是小丑啊

dmzj插件不是国人在用，国人在维护？发中文有问题？项目有禁止发中文了？你tm是有多自卑。

**Comment by Zxilly** [comment]
@ZerOri 
![image](https://user-images.githubusercontent.com/31370133/122157193-ff659700-ce9c-11eb-8e51-b6e37bda0c66.png)
万花丛中一只🤡，我就不说是谁了

**Comment by Zxilly** [comment]
哦，还有一只陪你一起的，你并不孤单啊

**Comment by sotha-sil-zen** [comment]
你是不是以为自己很明事理

**Comment by develon2015** [comment]
大号出来讲话

**Comment by leung13** [comment]
> 你是不是以为自己很明事理

那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴

**Comment by sotha-sil-zen** [comment]
> > 你是不是以为自己很明事理
> 
> 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴

收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^

**Comment by leung13** [comment]
> > > 你是不是以为自己很明事理
> > 
> > 
> > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> 
> 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^

哈哈哈 我笑了 你什么人阿 你打着简体字就在叫了？好歹换个繁体字阿 你是国人的话这样不就是黑了自己^^  还有看了你的仓库的 is-thirteen我想笑啊 ^^ 我以为什么东西  狗都会写的东西你好意思放上来阿？老子玩JVM源码的时候你还在你妈肚子里 可惜你现在没有妈妈了^^

**Comment by sotha-sil-zen** [comment]
> > > > 你是不是以为自己很明事理
> > > 
> > > 
> > > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> > 
> > 
> > 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^
> 
> 哈哈哈 我笑了 你什么人阿 你打着简体字就在叫了？好歹换个繁体字阿 你是国人的话这样不就是黑了自己^^ 还有看了你的仓库的 is-thirteen我想笑啊 ^^ 我以为什么东西 狗都会写的东西你好意思放上来阿？老子玩JVM源码的时候你还在你妈肚子里 可惜你现在没有妈妈了^^

自嘲完美，别人fork个整活的repo就立成靶子一通乱打，恁一年连个commit都没有，也没有开放的repo供人评鉴，直说自己JAVA大手子，我暂且蒙在鼓里，，，

**Comment by isherryforever** [comment]
> > > 你是不是以为自己很明事理
> > 
> > 
> > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> 
> 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^

支你妈，湾湾仔

**Comment by leung13** [comment]
> > > > > 你是不是以为自己很明事理
> > > > 
> > > > 
> > > > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> > > 
> > > 
> > > 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^
> > 
> > 
> > 哈哈哈 我笑了 你什么人阿 你打着简体字就在叫了？好歹换个繁体字阿 你是国人的话这样不就是黑了自己^^ 还有看了你的仓库的 is-thirteen我想笑啊 ^^ 我以为什么东西 狗都会写的东西你好意思放上来阿？老子玩JVM源码的时候你还在你妈肚子里 可惜你现在没有妈妈了^^
> 
> 自嘲完美，别人fork个整活的repo就立成靶子一通乱打，恁一年连个commit都没有，也没有开放的repo供人评鉴，直说自己JAVA大手子，我暂且蒙在鼓里，，，

哈哈 我就不上大号 怎么样 你这点前端皮毛就别叫了好吧？   而且你哪国人阿？回应下 别回避呀 我看你就是学生狗一个  自以为是 还叫嚣“支*” 都不好意思承认自己身份了是吧？ 你这种人不是蠢就是坏

**Comment by leung13** [comment]
> > > > 你是不是以为自己很明事理
> > > 
> > > 
> > > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> > 
> > 
> > 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^
> 
> 支你妈，湾湾仔

这就是国人在装在黑自己 看他代码都是简体字

**Comment by sotha-sil-zen** [comment]
My Bad,对索多玛的人竟然还有一丝幻想，，，

**Comment by isherryforever** [comment]
> > > > > 你是不是以为自己很明事理
> > > > 
> > > > 
> > > > 那你告诉我什么叫明事理？整个这样的东西就叫明事理吗 整个这样的东西就叫明事理吗？真要打脸别就写个硬东西出来 别光只有把嘴
> > > 
> > > 
> > > 收收你的支味，自己没有历史的观念还要向别人喷污水，非要用立场取代理性，支人就是这种根性吗？^^
> > 
> > 
> > 支你妈，湾湾仔
> 
> 这就是国人在装在黑自己 看他代码都是简体字

那他可能没马

**Comment by Baz2013** [comment]
终于吵起来了！GREAT

**Comment by xiaop1ng** [comment]
急了急了
